---
- hosts: nginx_nodes
  become: yes
  tasks:
    - name: "Install the nginx rpm from a remote repo"
      yum:
        name: http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.15.6-1.el7_4.ngx.x86_64.rpm
        state: present
        
    - name: "Start service nginx, if not started"
      service:
        name: nginx
        state: restarted    